name: Trigger RD ECR

on: [push]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Tigger
        run: |
          curl -X POST https://api.github.com/repos/olxbr/devtools-scripts/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -H 'Authorization: token ${{ secrets.PAT }}' \
            --data '{"event_type": "ecr-push", "client_payload": { "version": "${GITHUB_REF#refs/heads/}", "pr_number": "${{ github.event.pull_request.number }}" }}'
